module.exports = {
  API: 'https://api.steemit.com',
  SLEEP_TIME: 60 * 1000,
  UPVOTE_DELAY_SECONDS: 32 * 60,
  BLOCKS_PER_BATCH: 100,
  WEEKLY_BLOCKS: 7 * 24 * 60 * 20,
  STREAM_FETCHERS_QUEUE: 'STREAM_FETCHERS_QUEUE',
  PAST_FETCHERS_QUEUE: 'PAST_FETCHERS_QUEUE',
  STREAM_UPVOTERS_QUEUE: 'STREAM_UPVOTERS_QUEUE',
  PAST_UPVOTERS_QUEUE: 'PAST_UPVOTERS_QUEUE',
};
