module.exports = {
  API: 'https://api.steemit.com',
  SLEEP_TIME: 60 * 1000,
  BLOCKS_PER_BATCH: 100,
  WEEKLY_BLOCKS: 7 * 24 * 60 * 20,
  STREAM_FETCHERS_QUEUE: 'STREAM_FETCHERS_QUEUE',
  PAST_FETCHERS_QUEUE: 'PAST_FETCHERS_QUEUE',
  UPVOTERS_QUEUE: 'UPVOTERS_QUEUE',
};
